version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/rws"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/spa"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"