services:
  rws:
    build:
      context: ./rws
    container_name: rws-metroweb
    ports:
      - "8080:8080"

  spa:
    build:
      context: ./spa
    container_name: spa-metroweb
    ports:
      - "3000:3000"
    depends_on:
      - rws
