name: Qodana

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2026.2
        with:
          pr-mode: false
          use-caches: true
          use-annotations: true
          upload-result: false
          push-fixes: none